version: '3.8'

services:
  microservicio-pdf:
    build: .
    container_name: siscomat-pdf
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # para poder conectarse con el backend
    networks: 
      - siscomat_network

# para poder conectarse con el backend
networks:
  siscomat_network:
    external: true